---
title: "candys"
author: "Juan Ignacio De Vicente"
date: "2022-10-25"
output: html_document
---

A list of any assumptions you have made
The steps you took to clean the data (you don’t need to write out in detail every step, but a combination of commented code chunks with surrounding overall explanations would be great).
The answers to the questions presented in the task brief
Any other interesting analyses or conclusions you come across.


#### **A brief Introduction to the dataset**

Who doesn't like candys? This data set is an overview about the consumers' taste during the years 2015,2016 and 2017. This survey was carry out in USA,so mainly it reflected the candy context in that country.However, there were a small proportion of participants from others countries.




#### **Assumptions**

My first assumption was before open the Task, I already knew I would have a lot of issues with the data in every stage of the process from star cleaning to answered the questions.

After the cleaning process - you never finish- I understood I should have a clear understandable of the data and the questions and a strategic before start tiding about columns/ variables (rename, keep or remove, class of data, number of columns per year), or rows/ observations ( leave or remove NA, ) 

