---
title: "R Notebook"
output: html_notebook
---
write_csv(clean_decathlon,"clean_data/clean_decathlon.csv")

```{r}
write_csv(clean_decathlon,"clean_data/clean_decathlon.csv")
```

```{r}
library(tidyverse)




```

```{r}
#Questions 1.Who had the longest long jump seen in the data?

 longest_jump <- rename_clean_deca %>%
  select(name,long_jump) %>% 
  arrange(desc(long_jump))%>% 
  head(1)

longest_jump

```

```{r}
#2 What was the average 100m time in each competition?

average_time <- rename_clean_deca %>%
  select (`run_100m`, competition) %>% 
  group_by (competition) %>% 
  summarise(avg_time_competition = mean(`run_100m`))
            
average_time

```


```{r}
# 3  Who had the highest total points across both competitions?

total_points <- rename_clean_deca %>%
  arrange(desc(points))

total_points

```

```{r}
#Q4.#  4 What was the shot_put scores for the top three competitors in each competition?

shot_put_score <- rename_clean_deca %>% 
   select(competition,shot_put, name) %>% 
    arrange (shot_put) %>% 
     group_by(competition) %>% 
     slice_max(competition, n = 3, with_ties = FALSE)

shot_put_score
```

```{r}
#   5 What was the average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds?

average_points_400 <- rename_clean_deca %>% 
  group_by(name)
 
  group_by(mtcars, cyl) %>%                ## group by cylinder
# mutate(rank = row_number(mpg)) %>%   ## rank by mpg
#   filter(rank <= 3) %>%                ## top three for each cyl
#   arrange(rank) %>%                    ## arrange each group by rank
#   ungroup() %>%                        ## remove grouping
#   arrange(desc(cyl))                   ## arrange all by cylinder (descending)

```








```{r}

#   5 What was the average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds?

# 
# # group_by(mtcars, cyl) %>%                ## group by cylinder
# mutate(rank = row_number(mpg)) %>%   ## rank by mpg
#   filter(rank <= 3) %>%                ## top three for each cyl
#   arrange(rank) %>%                    ## arrange each group by rank
#   ungroup() %>%                        ## remove grouping
#   arrange(desc(cyl))                   ## arrange all by cylinder (descending)
# 
# 
# avg_points(400<50) , avg_points(400>50)
```

